# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '9.0'
use_frameworks!

target 'TwitterClient' do
	pod 'AFNetworking'
	pod 'BDBOAuth1Manager'
	pod 'SwiftyJSON'
	pod 'MBProgressHUD'
end

